### ISSUE TITLE
whitelist file extension validation seems broken

### ISSUE THREAD

**Issue by iamliamnorton** [carrierwaveuploader/carrierwave-datamapper#20]
https://github.com/jnicklas/carrierwave

When using file extension whitelist, datamapper should fail validation when saving if the extension isn't valid. This doesn't seem to be happening.

**Comment by conraddecker** [comment]
I can't figure out how to make this happen either. Is there any insight into where we might be able to enable this by chance? From what I can tell, CarrierWave is raising an Exception: 

``` ruby
Exception `CarrierWave::IntegrityError' at xxx/carrierwave-0.8.0/lib/carrierwave/uploader/extension_whitelist.rb:43 - translation missing: en.errors.messages.extension_white_list_error 
```

followed by 

``` ruby
Exception `DataObjects::DataError' at xxx/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:194 - Data too long for column 'avatar' at row 1
```

Based on some additional information I found, I figured I could add a validation in my User model like so

``` ruby
validates_integrity_of :avatar
```

Upon doing so, however, I received a `method_missing` error for that method. Apologies if I'm missing something glaring here, I'm still pretty new to ruby and this is my first time using CW.

Thanks in advance for any help.
