### ISSUE TITLE
Generator fails

### ISSUE THREAD

**Issue by 1xch** [carrierwaveuploader/carrierwave-datamapper#5]
I haven't used carrierwave in a while, but installing today I get a ton of issues.

in gem file:
RAILS_VERSION = '~> 3.0.7'
DM_VERSION    = '~> 1.1.0'
gem 'carrierwave-datamapper', :require => 'carrierwave/datamapper'

running 'rails generate uploader userasset'

The primary error is - 
.../.rvm/gems/ruby-1.9.2-p180/gems/carrierwave-datamapper-0.1.1/lib/carrierwave/datamapper.rb:8:in `module:DataMapper': uninitialized constant CarrierWave::Mount (NameError)

I have Datamapper running for this application (development - sqlite), I've used carrierwave before, but not the apparent recent dm specific version.

Let me know what else I can provide...I'm not sure if this is my setup or this gem right now, but I can do nothing with it, the error above at every step.

**Comment by trevorturk** [comment]
I think the generator is only for Active Record, no?

**Comment by 1xch** [comment]
Yeah, the new dm instructions are not explcit about requiring both carrierwave and carriewave-datamapper

gem 'carrierwave'
gem 'carrierwave-datamapper', :require => 'carrierwave/datamapper'

after that, I had no problems.

**Comment by trevorturk** [comment]
Pull request please?
