### ISSUE TITLE
Uploaded files are never stored in store_dir which breaks file.url?

### ISSUE THREAD

**Issue by jgavert** [carrierwaveuploader/carrierwave-datamapper#8]
Hello

I discovered that I could easily upload images to my sinatra, datamapper using carrierwave.

The problems is that the files that I have uploaded don't get saved to my store_dir and so the url that file.url command provides looks very much bugged. 

The code looks something like this...

model.rb

<pre><code>class MyUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  def extension_white_list
    %w(jpg jpeg gif png)
  end

  version :thumb do
    process :resize_to_fill => [200,200]
  end

  storage :file
end

class Image
  include DataMapper::Resource

  property :id, Serial

  mount_uploader :file, MyUploader
end</code></pre>

main.rb

<pre><code>before do
  @images = Image.all
  @categories = Category.all :order => :id.desc
end

...

get '/image' do
  haml :image
end

...

post '/image' do
  image = Image.new
  image.file = params[:image]
  image.save!
  redirect '/image'
end</code></pre>

image.haml

<pre><code>#add
  %section
    %form{:action => "/image", :method => "post", :enctype => "multipart/form-data"}
      %input{:type => "file", :name => "image"}
      %input{:type => "submit", :value => "Upload"}
#image
  - @images.each do |image|
    %img{:src => image.file.url}</code></pre>

result html on page, uploaded files name: test.png

<pre><code>
img src="/public/upload/typeimage/pngtempfile#<File:0x7fab3b13a680>filenametest.pngnameimageheadContent-Disposition: form-data; name="image"; filename="test.png" Content-Type: image/png"
</code></pre>

My friend suggested that I would make new issua about it and he's the course instructor. The project is named "Tsoha" if you want to reproduce what I'm seeing.

**Comment by trevorturk** [comment]
Would you mind uploading the entire app to github and linking to it here?

**Comment by jgavert** [comment]
This one right here:

https://github.com/fazias/Tsoha

**Comment by trevorturk** [comment]
Sorry, but I couldn't figure anything out straight away. 

@solnic, can you have a look if you have time?

**Comment by solnic** [comment]
@trevorturk sure I'll look into this

**Comment by solnic** [comment]
@fazias it doesn't work because you save image via a call to #save! and in DataMapper #save! (as well as #update!) bypasses the callbacks and in carrierwave-datamapper a callback is used to _store the file_. Just change #save! to #save and it's gonna work

**Comment by jgavert** [comment]
@solnic Oh! I was using the #save! quite freely. 

Everything works now very nicely!

Thanks for the help and patience.

**Comment by solnic** [comment]
@fazias cool :) btw why did you use #save! in the first place?

**Comment by jgavert** [comment]
There wasn't any deeper reason than when I got help from older student about datamapper saving problems that I had. He used it and I started to use it also.

**Comment by solnic** [comment]
@fazias I see. #save! is a "dangerous" version of #save because it bypasses the hooks which means it also bypasses validations, be careful with it and have fun with your project :)
