### ISSUE TITLE
mount_uploader does not respect options (such as :mount_on).

### ISSUE THREAD

**Issue by postmodern** [carrierwaveuploader/carrierwave-datamapper#9]
I noticed that the normal `mount_uploader` method supports a variety of options, such as `:mount_on`. carrierwave-datamapper accepts an options argument, but does nothing with it. I need to use the `:mount_on` option in order to upgrade from `dm-paperclip`.

**Comment by solnic** [comment]
@postmodern ok so this options arg should be just passed down to `mount_uploader`, right?

**Comment by postmodern** [comment]
Unsure exactly where you want to call `super`, but I assume so. Original [mount_uploader](https://github.com/jnicklas/carrierwave/blob/master/lib/carrierwave/mount.rb#L140-150) populates `uploader_options`.

**Comment by postmodern** [comment]
Ah my mistake. So the `:mount_on` option is in fact passed down to carrierwave's `mount_uploader`. Except `read_uploader` is aliased to `attribute_get`, which assumes there's a property of the given name (https://github.com/jnicklas/carrierwave/blob/master/lib/carrierwave/mount.rb#L293-303). Perhaps carrierwave-datamapper should support passing the `:field` option down to the uploader property when one needs to map an Uploader to an existing column (such as paperclip's `attachment_file_name`)?

**Comment by postmodern** [comment]
https://github.com/jnicklas/carrierwave-datamapper/pull/13 should allow carrierwave to use existing properties, without defining any new ones.
